name: flutter_assist
description: This package includes various utility functions and classes that aim to simplify some common tasks while working with Flutter.
version: 1.0.1
repository: https://github.com/UcGeorge/flutter_utils

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  file_picker: ^5.2.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_cache_manager: ^3.3.0
  flutter_svg: ^2.0.5
  google_maps_flutter: ^2.2.5
  image_picker: ^0.8.7+4
  intl: ^0.18.1
  logging: ^1.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
